// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	// No function defined for root command, so Execute expects a subcommand.
	// We can test that it fails with unknown command or usage.
	err = cmd.Execute([]string{"unknown-command"})
	if err == nil {
		t.Error("Expected error for unknown command, got nil")
	}

}
